linode instance

diff --git a/bin/gen_cert b/bin/gen_cert
--- a/bin/gen_cert
+++ b/bin/gen_cert
@@ -1,23 +1,59 @@
 #!/usr/bin/env bash
-set -e
-source .env
-# Create Root Key
-openssl genrsa -out .${BUILD_ENV}/rootCA.pem 4096
-# Create and self sign the Root Certificate
-openssl req -x509 -new -nodes \
-    -key .${BUILD_ENV}/rootCA.pem \
-    -sha256 -days 30 \
-    -out .${BUILD_ENV}/rootCA.crt \
-    -subj "/C=AU/O=Trivial Security/OU=Trivial Security Certification Authority"
-
 if ! [ -x "$(command -v certutil)" ]; then
   echo '[INFO] certutil is not installed' >&2
   exit 0
 fi
 
+set -e
+source .env
+# Create Root Key
+openssl genrsa -out .${BUILD_ENV}/cacert/rootCA.pem 4096
+# Create and self sign the Root Certificate
+openssl req -x509 -new -nodes \
+    -key .${BUILD_ENV}/cacert/rootCA.pem \
+    -sha256 -days 30 \
+    -out .${BUILD_ENV}/cacert/rootCA.crt \
+    -subj "/C=AU/CN=trivialsec.com/O=Trivial Security Pty Ltd/OU=Trivial Security Certification Authority"
+
+if ! [ -f .${BUILD_ENV}/domains.txt ]; then
+  echo ".${BUILD_ENV}/domains.txt not found, exiting..."
+  exit 0
+fi
+declare -a domains=($(cat .${BUILD_ENV}/domains.txt))
+readonly rsa_key_size=4096
+
+for domain in "${domains[@]}"; do
+  path=".${BUILD_ENV}/certs/${domain}"
+  mkdir -p ${path}
+  echo "Generating rsa:${rsa_key_size} x509 certificate for ${domain}"
+  # Create the certificate key
+  openssl genrsa -out ${path}/privkey.pem ${rsa_key_size}
+  # Create the signing (csr)
+  openssl req -new -sha256 \
+    -key ${path}/privkey.pem \
+    -subj "/C=AU/O=Trivial Security Pty Ltd/OU=Trivial Security/CN=${domain}" \
+    -out ${path}/root.csr
+  # Verify the csr's content
+  openssl req -in ${path}/root.csr -noout -text
+  # Generate the certificate using the root.csr and privkey.pem with the CA Root key
+  openssl x509 -req \
+    -in ${path}/root.csr \
+    -CA .${BUILD_ENV}/cacert/rootCA.crt \
+    -CAkey .${BUILD_ENV}/cacert/rootCA.pem \
+    -CAcreateserial \
+    -extfile <(cat .${BUILD_ENV}/v3.ext \
+        <(printf "DNS.1 = ${domain}")) \
+    -out ${path}/fullchain.pem \
+    -days 30 -sha256
+  # Verify the certificate
+  openssl x509 -in ${path}/fullchain.pem -text -noout
+  rm ${path}/root.csr
+
+done
+
 # Add to trust store
 certutil -d sql:$HOME/.pki/nssdb -D -n trivialsec || true
-certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n trivialsec -i .development/rootCA.crt
+certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n trivialsec -i .${BUILD_ENV}/cacert/rootCA.crt
 # Verify trust store
 certutil -d sql:$HOME/.pki/nssdb -L -n trivialsec
 
